<?php
		include('../function/connection.php');
		header("Content-Type:   application/vnd.ms-excel; charset=utf-8");
		header("Content-type:   application/x-msexcel; charset=utf-8");
		header("Content-Disposition: attachment; filename=abc.xls"); 
		header("Expires: 0");
		header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
		header("Cache-Control: private",false);

	if(!isset($_GET['tanggal']) && !isset($_GET['status'])){
		$ref='semua';
		$dataquery=mysql_query("SELECT * FROM calonkaryawan");
		$report="Report Tampil Semua";
	}elseif($_GET['tanggal']){
		$ref='tanggal';
		$tanggal=$_GET['tanggal'];
		$report="Report by Date";
		$dataquery=mysql_query("SELECT * FROM calonkaryawan WHERE tgl_tes='$tanggal'");
	}elseif($_GET['status']=='lulus'){
		$ref='lulus';
		$report="Report by Lulus";
		$dataquery=mysql_query("SELECT * FROM calonkaryawan WHERE hasil_akhir='Lulus'");
	}elseif($_GET['status']=='tdk_lulus'){
		$ref='tdk_lulus';
		$report="Report by Tidak Lulus";
		$dataquery=mysql_query("SELECT * FROM calonkaryawan WHERE hasil_akhir='Tidak Lulus'");
	}
?>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="Book1_files/filelist.xml">
<style id="Book1_32565_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl1532565
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6332565
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6432565
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6532565
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:.5pt solid windowtext;
	background:#9BC2E6;
	mso-pattern:black none;
	white-space:nowrap;}
.xl6632565
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Book1_32565" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=875 style='border-collapse:
 collapse;table-layout:fixed;width:656pt'>
 <col width=64 span=2 style='width:48pt'>
 <col width=135 style='mso-width-source:userset;mso-width-alt:4937;width:101pt'>
 <col width=64 span=3 style='width:48pt'>
 <col width=99 style='mso-width-source:userset;mso-width-alt:3620;width:74pt'>
 <col width=107 style='mso-width-source:userset;mso-width-alt:3913;width:80pt'>
 <col width=130 style='mso-width-source:userset;mso-width-alt:4754;width:98pt'>
 <col width=84 style='mso-width-source:userset;mso-width-alt:3072;width:63pt'>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1532565 width=64 style='height:15.0pt;width:48pt'></td>
  <td class=xl1532565 width=64 style='width:48pt'></td>
  <td class=xl1532565 width=135 style='width:101pt'></td>
  <td class=xl1532565 width=64 style='width:48pt'></td>
  <td class=xl1532565 width=64 style='width:48pt'></td>
  <td class=xl1532565 width=64 style='width:48pt'></td>
  <td class=xl1532565 width=99 style='width:74pt'></td>
  <td class=xl1532565 width=107 style='width:80pt'></td>
  <td class=xl1532565 width=130 style='width:98pt'></td>
  <td class=xl1532565 width=84 style='width:63pt'></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1532565 style='height:15.0pt'></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl1532565 style='height:15.75pt'></td>
  <td colspan=9 class=xl6632565>Laporan Seleksi Masuk PT Maju Terus</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1532565 style='height:15.0pt'></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1532565 style='height:15.0pt'></td>
  <td class=xl6532565>ID</td>
  <td class=xl6532565 style='border-left:none'>Tanggal Tes</td>
  <td class=xl6532565 style='border-left:none'>Nama</td>
  <td class=xl6532565 style='border-left:none'>Divisi</td>
  <td class=xl6532565 style='border-left:none'>Alamat</td>
  <td class=xl6532565 style='border-left:none'>Tes Kesehatan</td>
  <td class=xl6532565 style='border-left:none'>Nilai Psikotes</td>
  <td class=xl6532565 style='border-left:none'>Nilai tulis</td>
  <td class=xl6532565 style='border-left:none'>Hasil Akhir</td>
 </tr>
 <?php
	if($dataquery){
		while($datarow=mysql_fetch_array($dataquery)){
			?>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1532565 style='height:15.0pt'></td>
  <td class=xl6332565 style='border-top:none'><?php echo $datarow['id']; ?></td>
  <td class=xl6332565 style='border-top:none;border-left:none'><?php echo $datarow['tgl_tes']; ?></td>
  <td class=xl6332565 style='border-top:none;border-left:none'><?php echo $datarow['nama']; ?></td>
  <td class=xl6332565 style='border-top:none;border-left:none'><?php echo $datarow['divisi']; ?></td>
  <td class=xl6332565 style='border-top:none;border-left:none'><?php echo $datarow['alamat']; ?></td>
  <td class=xl6332565 style='border-top:none;border-left:none'><?php echo $datarow['tes_kesehatan']; ?></td>
  <td class=xl6332565 style='border-top:none;border-left:none'><?php echo $datarow['psikotes']; ?></td>
  <td class=xl6332565 style='border-top:none;border-left:none'><?php echo $datarow['tes_tertulis']; ?></td>
  <td class=xl6332565 style='border-top:none;border-left:none'><?php echo $datarow['hasil_akhir']; ?></td>
 </tr>
 <?php
		}
	}
	?>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1532565 style='height:15.0pt'></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1532565 style='height:15.0pt'></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td colspan=2 class=xl6432565>Tanggal</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1532565 style='height:15.0pt'></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1532565 style='height:15.0pt'></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1532565 style='height:15.0pt'></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td class=xl1532565></td>
  <td colspan=2 class=xl6432565>HRD</td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=135 style='width:101pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=99 style='width:74pt'></td>
  <td width=107 style='width:80pt'></td>
  <td width=130 style='width:98pt'></td>
  <td width=84 style='width:63pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
